### PR TITLE
Add russian localization.

### PR DESCRIPTION
**Pull request by akhromets**
If translation of "Import" and "Export" words is too long, we can safely change it to "Импорт" and "Export". It is not 100% right translation, but it may be better for UI reasons.

### CODE REVIEW

**Comment by aahung** [comment]
I think it looks great! Thank you!

Screen Shot 2019-04-02 at 11 41 37 AM

**Comment by aahung** [comment]
I just need to change the second checkbox

**Comment by akhromets** [comment]
I also push some small changes, so you can check them now.

**Comment by aahung** [comment]
Also wider :D
Screen Shot 2019-04-02 at 11 46 23 AM

**Comment by aahung** [comment]
I have a question. Are the prints on your keyboard different from US keyboard? Is it an issue?

**Comment by akhromets** [comment]
Sorry for a lot of pushes. For the second one I'll recheck all things twice before make pull request.


> I have a question. Are the prints on your keyboard different from US keyboard? Is it an issue?

Yep, it has some differences from the U.S. keyboard.

**Comment by akhromets** [comment]
But I didn't found translation files for them.

**Comment by aahung** [comment]
> a lot of pushes

No worries, really appreciate the effort!

> didn't found translation files for them.

I  did not think about that... But since it is standardized I can do it myself later.

**Comment by akhromets** [comment]
> I did not think about that... But since it is standardized I can do it myself later.

I think it's not a really big problem for now. But maybe it should be great if you can replace some symbols' names for their representation. I mean replace "semicolon" with ";" or "Right Bracket" with "]". It makes UX more user-friendly I think and also make this part of application language independent.

**Comment by aahung** [comment]
Thanks for this good idea. Easy to do xD

**Pull request merged**
